# Site settings
title: evrl.com
email: casedeg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mostly technical musings by Cees de Groot. Expect Scala, Java, Python,
  Agile, devops, and whatnot.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://evrl.com" # the base hostname & protocol for your site
twitter_username: cdegroot
github_username: cdegroot

# Build settings
markdown: kramdown
highlighter: rouge
